print("=================================")
print("This is a test file for Python 3.11.4")
print("=================================")
print("This is a new file in the git-practice directory.")
print("I hope this works...")
print("=================================")